version: 2
# Reference variables.
references:
  docker_default: &docker_node_14
    working_directory: /tmp/app
    docker:
      - image: cimg/node:14.17
    environment:
      TZ: 'Asia/Taipei'

jobs:
  build:
    <<: *docker_node_14
    steps:
      - checkout
      - restore_cache:
          keys:
            - 210820-node-14-cache-{{checksum "yarn.lock"}}
            - 210820-node-14-cache
      - run:
          name: install dependencies
          command: |
            yarn config set cache-folder ~/.yarn-cache
            yarn --frozen-lockfile
      - run:
          name: run lint
          command: yarn run lint
      - run:
          name: run test
          command: yarn run testonly --no-cache --colors
      - save_cache:
          key: 210820-node-14-cache-{{checksum "yarn.lock"}}
          paths:
            - ~/.yarn-cache
            - ./node_modules
